package POJO;
// Generated 15-feb-2016 11:50:57 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private String calle;
     private String portal;
     private String piso;
     private Persona persona;

    public Direccion() {
    }

    public Direccion(String calle, String portal, String piso, Persona persona) {
       this.calle = calle;
       this.portal = portal;
       this.piso = piso;
       this.persona = persona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getPortal() {
        return this.portal;
    }
    
    public void setPortal(String portal) {
        this.portal = portal;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }




}


